/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author Abdel Razek - Nageh
 */
public class UserPass extends javax.swing.JFrame {

    /**
     * Creates new form UserPass
     */
    public UserPass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPasswordField_Password = new javax.swing.JPasswordField();
        jLabel_Password = new javax.swing.JLabel();
        jTextField_UserName = new javax.swing.JTextField();
        jLabel_UserName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPasswordField_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_PasswordActionPerformed(evt);
            }
        });
        jPasswordField_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_PasswordKeyPressed(evt);
            }
        });
        jPanel1.add(jPasswordField_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 190, -1));

        jLabel_Password.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel_Password.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_Password.setText("Password:");
        jPanel1.add(jLabel_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, -1));

        jTextField_UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_UserNameActionPerformed(evt);
            }
        });
        jTextField_UserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_UserNameKeyPressed(evt);
            }
        });
        jPanel1.add(jTextField_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 190, -1));

        jLabel_UserName.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel_UserName.setForeground(new java.awt.Color(0, 0, 204));
        jLabel_UserName.setText("User Name:");
        jPanel1.add(jLabel_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UserNameActionPerformed

    private void jPasswordField_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_PasswordActionPerformed

    private void jTextField_UserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_UserNameKeyPressed
         int  keyCode = evt.getKeyCode ( ) ;
         if (keyCode == KeyEvent.VK_ENTER){
         checkNamePass ();
         }
    }//GEN-LAST:event_jTextField_UserNameKeyPressed

    private void jPasswordField_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordKeyPressed
        int  keyCode = evt.getKeyCode ( ) ;
         if (keyCode == KeyEvent.VK_ENTER){
         checkNamePass ();
         }
    }//GEN-LAST:event_jPasswordField_PasswordKeyPressed

    public  void checkNamePass (){
    
         
         
        if ("Abd Elrazek".equals(jTextField_UserName.getText()) || jTextField_UserName.getText().equals( "Al-Hussary")){
            if ("admin".equals (jPasswordField_Password.getText())){
               
              UserPass us = new UserPass ();
               
			 
			   
               
            }
                
         }else{
            JOptionPane.showMessageDialog (null , "User Name Or Passwor is Invalid , try again please...");
        }
        
    }
    /**
     * @param args the command line arguments
     */
   public static void main() {
  
       java.awt.EventQueue.invokeLater(new Runnable() {
       public void run (){
        try {  
            Thread.sleep(500);
        }catch (Exception e){
        
        }
           UserPass u = new UserPass ();
                u.setVisible(true);
                u.setLocationRelativeTo(null);
                u.setTitle("LOGIN INTO DATABSE OF PERSON");
                u.setResizable(false);
                u.pack();
                
       }
       });
       
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Person.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Person.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Person.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Person.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
               
               
                
      
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Password;
    private javax.swing.JLabel jLabel_UserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_Password;
    private javax.swing.JTextField jTextField_UserName;
    // End of variables declaration//GEN-END:variables
}
